[{
  id: '2PxysbRPFLtrgwGqVVAhVnUesrydfuAUvJwZ3HXXuTTpSe',
  title: 'First shipment',
  sender: 'romashka',
  recipient: 'Roga i Kopita',
  from: 'Canada',
  to: 'Russia',
  device: '9838866f-44b4-4b37-8b83-c1e09a456967',
  departureDate: '2019.01.01',
  arrivalDate: '2019.01.07',
  policyId: undefined,
  conditionMin: '-15',
  conditionMax: '-5',
  conditionType: 'temperature sensitive',
  carrier: 'Example carrier',
  goods: [{
    id: 'IjnasdoUAHMSdqklwN<ASANDukq',
    description: 'basic description',
  }],
  claims: [],
  extraInfo: [],
  status: 'damaged',
}, {
  id: '2PxysbRPFLtrgwGqVVAhVnUesrydfuAUvJwZ3HXXuTTpSa',
  title: 'First shipment',
  sender: 'romashka 2',
  device: '9838866f-44b4-4b37-8b83-c1e09a456967',
  recipient: 'Roga i Kopita 2',
  from: 'Canada',
  to: 'Russia',
  conditionType: 'temperature sensitive',
  conditionMin: '-15',
  conditionMax: '-5',
  departureDate: '2019.01.08',
  arrivalDate: '2019.01.07',
  policyId: undefined,
  carrier: 'Example carrier',
  goods: [{
    id: 'test item',
    description: 'some item',
  }],
  claims: [],
  extraInfo: [],
  status: 'approved',
}]